on: workflow_dispatch
   

permissions:
  contents: read
  pages: write
  id-token: write

env:
  REPO_NAME: tvsmartx86brasil
  CODENAME: noble
  COMPONENTS: main
  ARCHITECTURES: amd64
  REPO_PATH: "CristianMartinsDeBairros2003/tvsmartx86brasil-packages"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_id: ${{ steps.upload-artifact.outputs.artifact-id }}
      keyring: ${{ steps.create-apt-repo.outputs.keyring }}
    steps:
      - name: Display changed files
        uses:
          with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: 'string'
            run: echo "${{ steps.changed-files.outputs.filenames }}"
    name: Publish APT
    uses: MauroDruwel/apt-repo-action@v4
  with:
          repo-name: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.PAT }}
          repo_supported_arch: |
            ${{ env.ARCHITECTURES }}
          repo_supported_version: |
            ${{ env.CODENAME }}
          file: ${{ steps.changed-files.outputs.filenames }}
          file_target_version: noble
          public_key: ${{ secrets.PUBLIC }}
          private_key: ${{ secrets.PRIVATE }}
          key_passphrase: ${{ secrets.SECRET }}
          target_repository: ${{ env.REPO_PATH }}

